### ISSUE TITLE
How to choose industrial fieldbus when using dds-xrce

### ISSUE THREAD

**Issue by peak0924** [eProsima/Micro-XRCE-DDS#142]
In the field of power grid, we use RS-232 or RS-485 as the data transmission channel, and in the field of automobile, we use can bus as the transmission channel. Is there an official recommendation on which bus should be used for dds-xrce to achieve the best use effec

**Comment by pablogs9** [comment]
The transport selection highly depends on the platform and the use case. As you can see in the [documentation](https://micro-xrce-dds.docs.eprosima.com/en/stable/), Micro XRCE-DDS can handle multiple transport layers by providing mechanisms such as framing or reliability.

If you need commercial support for your specific use case, eProsima provides consulting services and architectural studies. Do not hesitate to contact our sales department at mariamerlan@eprosima.com.
