### ISSUE TITLE
Simple tutorial needed for uploading code to micro controller

### ISSUE THREAD

**Issue by Russ76** [eProsima/Micro-XRCE-DDS#163]
This software may be great and work well, and the Quick Start page for a sample app (publishing and subscribing on local) works, but a simple "Quick Start" is needed for getting the code into the micro controller, too! The user may be spared details of memory locations and process connections, he just wants his ROS2 code to work on the micro controller. And the micro controller should be able to handle complicated messages, such as cmd_vel, imu data, quat navigation messages, etc.

**Comment by pablogs9** [comment]
Out of scope.
