### ISSUE TITLE
Running foxglove bridge and foxglove client causes DDS to freeze

### ISSUE THREAD

**Issue by AlexKlimaj** [eProsima/Micro-XRCE-DDS#166]
When running dds and foxglove bridge on the target and foxglove studio on the dev PC, I get random lock ups of dds on the target that require restarting dds. This only appears to happen when foxglove studio is running on the dev pc.

**Comment by pablogs9** [comment]
Is there any way to reproduce it or at least some more details about your setup?

**Comment by AlexKlimaj** [comment]
This may have been an issue with the serial driver in nuttx on the client side.
