### ISSUE TITLE
client with only one reader instance cannot get session status

### ISSUE THREAD

**Issue by MarvinLiuMing** [eProsima/Micro-XRCE-DDS#167]
hi teams

I found a issue, the client in my MCU is only have one reader. I'm using uxr_run_session_time to get the data.

everything goes well except one thing, if xrce agent is killed, Client can't get this info by calling uxr_run_session_time function. I'm using reliable_out stream.

I have checked the code, maybe I think is necessry to invoke write_submessage_heartbeat function every time if there no data to send, instead of according to the result of uxr_update_output_stream_heartbeat_timestamp.

or I lost something ?  

Thanks in advance.

**Comment by pablogs9** [comment]
This is not an issue. The XRCE Wire protocol is working as expected. If you need to be aware of the Agent status from Client side you can use the ping API: https://micro-xrce-dds.docs.eprosima.com/en/latest/client_api.html?highlight=ping#general-utilities

**Comment by MarvinLiuMing** [comment]
Thanks for your reply. Got it , so if there is only one reader in the client, ping function is necessary. 
what is the practice of this part ? Even though I have periodic pub function, do I aslo need to ping agent periodically?

**Comment by pablogs9** [comment]
Yes, you will need to ping the agent periodically to check if it is still alive. You can configure the client to regenerate the entities if necessary, please read the creation documentation: https://micro-xrce-dds.docs.eprosima.com/en/latest/client.html#creation-policy-table

**Comment by MarvinLiuMing** [comment]
understand  thanks!
