### ISSUE TITLE
example HelloWorld doesn't receive anything

### ISSUE THREAD

**Issue by ghost** [eProsima/Micro-XRCE-DDS#17]
Hello,

I am currently using the most recent version of your software. I was able to build everything without problems. But the HelloWorld example doesn't seem to work and I'm not sure if it's just the example or if there's a problem deeper in the code.
I first run the agent with `./MicroXRCEAgent udp 2018` from `/usr/local/bin`, then publisher from the PublishHelloWorld directory and finally the subscriber from the SubscriberHelloWorld directory.
The publisher starts immediately to publish. When I start the subscriber, the agent says:
```
RTPS Participant matched 1.f.cc.79.2b.13.0.0.0.0.0.0|0.0.1.c1
RTPS Participant matched 1.f.cc.79.1e.13.0.0.0.0.0.0|0.0.1.c1
RTPS Participant matched 1.f.cc.79.1e.13.0.0.1.0.0.0|0.0.1.c1
```
But the subscriber actually gives no output, so I assume it isn't receiving anything from the publisher. Can you reproduce this?

Thank you and have a nice week!

**Comment by lemunozm** [comment]
Hi @ToRaVe, we have tested it and everything works for us. 
What the agent says is a little bit weird for me. The correct agent output must be the following (in an enviroment with only the example):

1. Run the agent:
    ```
    UDP agent initialization... OK
    Enter 'q' for exit
    ```
2. Run the publisher:
    The agent should not show any output because  there are no matches.
3. Run the subscriber (the output can be disordered):
    ```
    RTPS Participant matched ...
    RTPS Participant matched ...
    RTPS Subscriber matched ...
    RTPS Publisher matched ...
   ```
    Because each pair (participant, publisher) and (participant, subscriber) matched only when the other exists.

Please, can you check and share us the agent output in these 3 steps?
