### ISSUE TITLE
CycloneDDS and eProsima Micro XRCE-DDS Communication in ROS2

### ISSUE THREAD

**Issue by yigitboracagiran** [eProsima/Micro-XRCE-DDS#176]
I'm currently working on a project on ROS2. I'm using STM32F446ZET6U on my controller circuit and ROS Humble in my computer. MicroROS (STM) is using eProsima Micro XRCE-DDS, Nav2 (ROS2-HUMBLE-NAV2) is using CycloneDDS. 
In default behavior when I send a goal with NAV2 and the goal becomes successful state, Nav2 should send a twist message which should stop to robot.
And this becomes my problem: Sometimes stop message doesn't reach to the STM and it causes robot turning around itself.
- Note: I don't know for sure if this is happening because of DDS's difference but this is the most reasonable reason.
- Note: Another thing I don't know is this could be also happening while robot is also going to somewhere but we can't know for sure because Nav2 sends twist messages all the time. If one message doesn't reach, next message will reach. (There are 10 ms time difference between 2 twist messages.)

**Comment by pablogs9** [comment]
Hello @yigitboracagiran Micro XRCE-DDS does not ensures compatibility with Cyclone DDS
