### ISSUE TITLE
Is an OS required for an XRCE client?

### ISSUE THREAD

**Issue by jwdinius** [eProsima/Micro-XRCE-DDS#53]
The examples presented in the documentation show linux and windows examples, but I am wondering if an XRCE client can be deployed bare-metal.  Is there an OS required for a client?

**Comment by pablogs9** [comment]
XRCE can be deployed bare-metal but it depends on `clock_gettime()` function and you should write some custom transport, check this: https://github.com/eProsima/Micro-XRCE-DDS-Client/blob/66df0a6df20063d246dd638ac3d33eb2e652fab2/CMakeLists.txt#L132

**Comment by jwdinius** [comment]
Thanks for addressing so promptly!
