### ISSUE TITLE
About release schedule

### ISSUE THREAD

**Issue by OpusK** [eProsima/Micro-XRCE-DDS#8]
Hi.

I do not know if it's ok to leave this topic here, but I do not have an e-mail reply, so I issue it here.

I have a question regarding Micro-XRCE-DDS release schedule.
I am currently seeing you adding a lot of features and changing the API name.
And I saw news about Micro XRCE-DDS rmw.

So, my question is :
When will this next release of rmw and Micro-XRCE-DDS(include beta version) be planned? 
Since we are planning to update our firmware starting from Micro-XRCE-DDS release, I would like to check schedule to some extent.

Thanks!

**Comment by BorjaOuterelo** [comment]
Hi @OpusK.

I sent an email to you with our plans.
