### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by vibnwis** [eProsima/Micro-XRCE-DDS#80]
Using the example code of PublishHelloWorld, I encountered the above errors.

Basically, I compiled it using the command below. In the example/PublishHelloWorld folder, I typed.
#gcc main.c HelloWorld.c -o HelloWorld -lmicrocdr -lmicroxrcedds_client
and run it by 
#./HelloWorld 127.0.0.1 2019

Any comments or suggestions are appreciated.

Thank you
V

**Comment by pablogs9** [comment]
Not able to reproduce: https://asciinema.org/a/3dXkrqEQP4bAMnzeYzgQTMx50

Reopen if you can provide a reproducible issue.

**Comment by vibnwis** [comment]
I followed the steps in the video. However, still ended with a segmentation fault. See
![Screenshot from 2021-04-07 21-57-27](https://user-images.githubusercontent.com/12945494/113848336-796a0780-97ec-11eb-86c6-bb47a3bcb70b.png)

**Comment by vibnwis** [comment]
As I keep installing micro-xrce-dds-client through the make install, I was wondering if it still gets the older version of the library?

**Comment by pablogs9** [comment]
Probably it is using an old version of the headers files, remove all references to XRCE-DDS Client in `/usr`

**Comment by vibnwis** [comment]
Check out the screenshot attached. Any unusual thingy? Which one should be removed?
![Screenshot from 2021-04-07 22-15-28](https://user-images.githubusercontent.com/12945494/113851001-22b1fd00-97ef-11eb-9bae-5cb03e3fba0c.png)

**Comment by pablogs9** [comment]
Remove all of them and then make a new `make install`

**Comment by vibnwis** [comment]
Yes, in the course of removing the client as the agent as well. 
Many thanks

Sincerely
