### ISSUE TITLE
In XRCE_DDS, can one system has two participants?

### ISSUE THREAD

**Issue by vibnwis** [eProsima/Micro-XRCE-DDS#84]
Assuming I have to separate systems but residing in one single hardware, can I have two participants, one for system A and one for system B, and the publishers of A can not reach subscribers B, and vice-versa? Appreciate your comments please?

**Comment by pablogs9** [comment]
Publisher in A should reach subscribers in B if client and agent are running in the same hardware and it has `localhost` network interface.

Provide a replicable scenario if you have had any problem.

**Comment by vibnwis** [comment]
I am now at the design stage. Hence I want to understand the concepts properly to avoid any silly mistake. Can I interpret your answers as, if there are several PCs and running those A and B systems. System A will not able to see system B and vice-versa?

**Comment by pablogs9** [comment]
Yes, A and B will see each other if they are using DDS to communicate.
