### ISSUE TITLE
Is that avariabled to publish through wireless

### ISSUE THREAD

**Issue by PierrePeng** [eProsima/Micro-XRCE-DDS#97]
Micro-XRCE-DDS is a wire protocol. 
1. Can I use Micro-XRCE-DDS to communicate through wireless?
2. If it can, what resources are needed for hardware support？

Thanks!

**Comment by pablogs9** [comment]
Hello @PierrePeng:

1. Yes, Micro XRCE-DDS defines a set of messages that are exchanged between the client and the agent. Those messages can be sent over a packet-oriented transport (UDP, TCP...) o a stream-oriented transport (UART, SPI...). So **yes** you should be able to use it in your wireless transport.
2. Can you describe your platform and use case? So I can provide details about how to use XRCE-DDS on it

Thanks!

**Comment by PierrePeng** [comment]
Hi @pablogs9 

Thanks for the reply. It's really useful for me.

As for the second question, we want to use freeRTOS on STM32.

Thanks
Pierre

**Comment by pablogs9** [comment]
Here you have an example of how to integrate FreeRTOS and Micro XRCE-DDS Client using STM32CubeMX: https://github.com/eProsima/Micro-XRCE-DDS-Apps/tree/microxrce_dev/FreeRTOS

I'm closing, do not hesitate to reopen if you have further questions.
